stages:
  - lint

golangci_lint:
  tags:
    - shared
    - debian
  stage: lint
  image: debian:bullseye
  before_script:
    - apt-get update && apt-get install -y curl unzip git
    - curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v2.1.6/golangci-lint-2.1.6-illumos-amd64.tar.gz | tar -xz
    - mv golangci-lint-*/golangci-lint /usr/local/bin/
  script:
    - cd go
    - golangci-lint run ./...
