/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The person who created the WAP.
 */
export type Author = string;

/**
 * Wochenarbeitsplan (WAP): schedule for a military week with events and logistical informations.
 */
export interface WAP {
  /**
   * Metadata concerning the WAP.
   */
  meta?: {
    author: Author;
    /**
     * Text to be displayed under the signing box
     */
    signerText?: string;
    /**
     * The earliest time displayed in the WAP. Given in format HH:MM
     */
    startTime?: string;
    /**
     * The latest time displayed in the WAP. Given in format HH:MM
     */
    endTime?: string;
    /**
     * The first day of the WAP. Given in format YYYY-MM-DD
     */
    firstDay: string;
    /**
     * The unit the WAP is for
     */
    unit?: string;
    /**
     * The title of the WAP. Often contains the week number.
     */
    title: string;
    /**
     * The version of the WAP or when it was last modified.
     */
    version?: string;
    [k: string]: unknown;
  };
  /**
   * Defines categories for events to display them styled.
   */
  categories?: {
    /**
     * Short identifier for the category. To be used as reference from events.
     */
    identifier: string;
    /**
     * Describes for what the category is used. Not to be printed.
     */
    comment?: string;
    /**
     * Color to give the category
     */
    color: string;
    /**
     * Color of the text in the category
     */
    textColor?: string;
    [k: string]: unknown;
  }[];
  /**
   * @minItems 1
   */
  weeks?: [
    {
      title?: string;
      /**
       * Additional remarks
       */
      remarks?: string[];
      /**
       * @minItems 7
       * @maxItems 7
       */
      days: [
        {
          title?: string;
          /**
           * The columns this day is subdivided in. Can be refered by appearsIn for events.
           *
           * @minItems 1
           */
          columns?: [string, ...string[]];
          /**
           * Tagesbemerkungen
           */
          remarks?: {
            /**
             * The text to be printed as a remark
             */
            title: string;
            /**
             * Optional Start-Time
             */
            start?: string;
            /**
             * Optional End-Time
             */
            end?: string;
            [k: string]: unknown;
          }[];
          /**
           * All events that occur on this day.
           */
          events?: {
            /**
             * Title of the event.
             */
            title: string;
            /**
             * Start time. In format HH:MM
             */
            start: string;
            /**
             * End time. In format HH:MM
             */
            end: string;
            /**
             * if the event is open-ended
             */
            openEnd?: boolean;
            /**
             * Additional information such as the responsible person or the location.
             */
            description?: string;
            /**
             * Identifer of a defined category.
             */
            category?: string;
            /**
             * Columns in which this event should appear.
             */
            appearsIn?: string[];
            /**
             * if the event repeats periodically.
             */
            repeats?: "no" | "daily" | "weekly";
            /**
             * This forces the text to appear horizontal
             */
            forceHorizontalText?: boolean;
            zIndex?: number;
            [k: string]: unknown;
          }[];
          [k: string]: unknown;
        },
        {
          title?: string;
          /**
           * The columns this day is subdivided in. Can be refered by appearsIn for events.
           *
           * @minItems 1
           */
          columns?: [string, ...string[]];
          /**
           * Tagesbemerkungen
           */
          remarks?: {
            /**
             * The text to be printed as a remark
             */
            title: string;
            /**
             * Optional Start-Time
             */
            start?: string;
            /**
             * Optional End-Time
             */
            end?: string;
            [k: string]: unknown;
          }[];
          /**
           * All events that occur on this day.
           */
          events?: {
            /**
             * Title of the event.
             */
            title: string;
            /**
             * Start time. In format HH:MM
             */
            start: string;
            /**
             * End time. In format HH:MM
             */
            end: string;
            /**
             * if the event is open-ended
             */
            openEnd?: boolean;
            /**
             * Additional information such as the responsible person or the location.
             */
            description?: string;
            /**
             * Identifer of a defined category.
             */
            category?: string;
            /**
             * Columns in which this event should appear.
             */
            appearsIn?: string[];
            /**
             * if the event repeats periodically.
             */
            repeats?: "no" | "daily" | "weekly";
            /**
             * This forces the text to appear horizontal
             */
            forceHorizontalText?: boolean;
            zIndex?: number;
            [k: string]: unknown;
          }[];
          [k: string]: unknown;
        },
        {
          title?: string;
          /**
           * The columns this day is subdivided in. Can be refered by appearsIn for events.
           *
           * @minItems 1
           */
          columns?: [string, ...string[]];
          /**
           * Tagesbemerkungen
           */
          remarks?: {
            /**
             * The text to be printed as a remark
             */
            title: string;
            /**
             * Optional Start-Time
             */
            start?: string;
            /**
             * Optional End-Time
             */
            end?: string;
            [k: string]: unknown;
          }[];
          /**
           * All events that occur on this day.
           */
          events?: {
            /**
             * Title of the event.
             */
            title: string;
            /**
             * Start time. In format HH:MM
             */
            start: string;
            /**
             * End time. In format HH:MM
             */
            end: string;
            /**
             * if the event is open-ended
             */
            openEnd?: boolean;
            /**
             * Additional information such as the responsible person or the location.
             */
            description?: string;
            /**
             * Identifer of a defined category.
             */
            category?: string;
            /**
             * Columns in which this event should appear.
             */
            appearsIn?: string[];
            /**
             * if the event repeats periodically.
             */
            repeats?: "no" | "daily" | "weekly";
            /**
             * This forces the text to appear horizontal
             */
            forceHorizontalText?: boolean;
            zIndex?: number;
            [k: string]: unknown;
          }[];
          [k: string]: unknown;
        },
        {
          title?: string;
          /**
           * The columns this day is subdivided in. Can be refered by appearsIn for events.
           *
           * @minItems 1
           */
          columns?: [string, ...string[]];
          /**
           * Tagesbemerkungen
           */
          remarks?: {
            /**
             * The text to be printed as a remark
             */
            title: string;
            /**
             * Optional Start-Time
             */
            start?: string;
            /**
             * Optional End-Time
             */
            end?: string;
            [k: string]: unknown;
          }[];
          /**
           * All events that occur on this day.
           */
          events?: {
            /**
             * Title of the event.
             */
            title: string;
            /**
             * Start time. In format HH:MM
             */
            start: string;
            /**
             * End time. In format HH:MM
             */
            end: string;
            /**
             * if the event is open-ended
             */
            openEnd?: boolean;
            /**
             * Additional information such as the responsible person or the location.
             */
            description?: string;
            /**
             * Identifer of a defined category.
             */
            category?: string;
            /**
             * Columns in which this event should appear.
             */
            appearsIn?: string[];
            /**
             * if the event repeats periodically.
             */
            repeats?: "no" | "daily" | "weekly";
            /**
             * This forces the text to appear horizontal
             */
            forceHorizontalText?: boolean;
            zIndex?: number;
            [k: string]: unknown;
          }[];
          [k: string]: unknown;
        },
        {
          title?: string;
          /**
           * The columns this day is subdivided in. Can be refered by appearsIn for events.
           *
           * @minItems 1
           */
          columns?: [string, ...string[]];
          /**
           * Tagesbemerkungen
           */
          remarks?: {
            /**
             * The text to be printed as a remark
             */
            title: string;
            /**
             * Optional Start-Time
             */
            start?: string;
            /**
             * Optional End-Time
             */
            end?: string;
            [k: string]: unknown;
          }[];
          /**
           * All events that occur on this day.
           */
          events?: {
            /**
             * Title of the event.
             */
            title: string;
            /**
             * Start time. In format HH:MM
             */
            start: string;
            /**
             * End time. In format HH:MM
             */
            end: string;
            /**
             * if the event is open-ended
             */
            openEnd?: boolean;
            /**
             * Additional information such as the responsible person or the location.
             */
            description?: string;
            /**
             * Identifer of a defined category.
             */
            category?: string;
            /**
             * Columns in which this event should appear.
             */
            appearsIn?: string[];
            /**
             * if the event repeats periodically.
             */
            repeats?: "no" | "daily" | "weekly";
            /**
             * This forces the text to appear horizontal
             */
            forceHorizontalText?: boolean;
            zIndex?: number;
            [k: string]: unknown;
          }[];
          [k: string]: unknown;
        },
        {
          title?: string;
          /**
           * The columns this day is subdivided in. Can be refered by appearsIn for events.
           *
           * @minItems 1
           */
          columns?: [string, ...string[]];
          /**
           * Tagesbemerkungen
           */
          remarks?: {
            /**
             * The text to be printed as a remark
             */
            title: string;
            /**
             * Optional Start-Time
             */
            start?: string;
            /**
             * Optional End-Time
             */
            end?: string;
            [k: string]: unknown;
          }[];
          /**
           * All events that occur on this day.
           */
          events?: {
            /**
             * Title of the event.
             */
            title: string;
            /**
             * Start time. In format HH:MM
             */
            start: string;
            /**
             * End time. In format HH:MM
             */
            end: string;
            /**
             * if the event is open-ended
             */
            openEnd?: boolean;
            /**
             * Additional information such as the responsible person or the location.
             */
            description?: string;
            /**
             * Identifer of a defined category.
             */
            category?: string;
            /**
             * Columns in which this event should appear.
             */
            appearsIn?: string[];
            /**
             * if the event repeats periodically.
             */
            repeats?: "no" | "daily" | "weekly";
            /**
             * This forces the text to appear horizontal
             */
            forceHorizontalText?: boolean;
            zIndex?: number;
            [k: string]: unknown;
          }[];
          [k: string]: unknown;
        },
        {
          title?: string;
          /**
           * The columns this day is subdivided in. Can be refered by appearsIn for events.
           *
           * @minItems 1
           */
          columns?: [string, ...string[]];
          /**
           * Tagesbemerkungen
           */
          remarks?: {
            /**
             * The text to be printed as a remark
             */
            title: string;
            /**
             * Optional Start-Time
             */
            start?: string;
            /**
             * Optional End-Time
             */
            end?: string;
            [k: string]: unknown;
          }[];
          /**
           * All events that occur on this day.
           */
          events?: {
            /**
             * Title of the event.
             */
            title: string;
            /**
             * Start time. In format HH:MM
             */
            start: string;
            /**
             * End time. In format HH:MM
             */
            end: string;
            /**
             * if the event is open-ended
             */
            openEnd?: boolean;
            /**
             * Additional information such as the responsible person or the location.
             */
            description?: string;
            /**
             * Identifer of a defined category.
             */
            category?: string;
            /**
             * Columns in which this event should appear.
             */
            appearsIn?: string[];
            /**
             * if the event repeats periodically.
             */
            repeats?: "no" | "daily" | "weekly";
            /**
             * This forces the text to appear horizontal
             */
            forceHorizontalText?: boolean;
            zIndex?: number;
            [k: string]: unknown;
          }[];
          [k: string]: unknown;
        }
      ];
      [k: string]: unknown;
    },
    ...{
      title?: string;
      /**
       * Additional remarks
       */
      remarks?: string[];
      /**
       * @minItems 7
       * @maxItems 7
       */
      days: [
        {
          title?: string;
          /**
           * The columns this day is subdivided in. Can be refered by appearsIn for events.
           *
           * @minItems 1
           */
          columns?: [string, ...string[]];
          /**
           * Tagesbemerkungen
           */
          remarks?: {
            /**
             * The text to be printed as a remark
             */
            title: string;
            /**
             * Optional Start-Time
             */
            start?: string;
            /**
             * Optional End-Time
             */
            end?: string;
            [k: string]: unknown;
          }[];
          /**
           * All events that occur on this day.
           */
          events?: {
            /**
             * Title of the event.
             */
            title: string;
            /**
             * Start time. In format HH:MM
             */
            start: string;
            /**
             * End time. In format HH:MM
             */
            end: string;
            /**
             * if the event is open-ended
             */
            openEnd?: boolean;
            /**
             * Additional information such as the responsible person or the location.
             */
            description?: string;
            /**
             * Identifer of a defined category.
             */
            category?: string;
            /**
             * Columns in which this event should appear.
             */
            appearsIn?: string[];
            /**
             * if the event repeats periodically.
             */
            repeats?: "no" | "daily" | "weekly";
            /**
             * This forces the text to appear horizontal
             */
            forceHorizontalText?: boolean;
            zIndex?: number;
            [k: string]: unknown;
          }[];
          [k: string]: unknown;
        },
        {
          title?: string;
          /**
           * The columns this day is subdivided in. Can be refered by appearsIn for events.
           *
           * @minItems 1
           */
          columns?: [string, ...string[]];
          /**
           * Tagesbemerkungen
           */
          remarks?: {
            /**
             * The text to be printed as a remark
             */
            title: string;
            /**
             * Optional Start-Time
             */
            start?: string;
            /**
             * Optional End-Time
             */
            end?: string;
            [k: string]: unknown;
          }[];
          /**
           * All events that occur on this day.
           */
          events?: {
            /**
             * Title of the event.
             */
            title: string;
            /**
             * Start time. In format HH:MM
             */
            start: string;
            /**
             * End time. In format HH:MM
             */
            end: string;
            /**
             * if the event is open-ended
             */
            openEnd?: boolean;
            /**
             * Additional information such as the responsible person or the location.
             */
            description?: string;
            /**
             * Identifer of a defined category.
             */
            category?: string;
            /**
             * Columns in which this event should appear.
             */
            appearsIn?: string[];
            /**
             * if the event repeats periodically.
             */
            repeats?: "no" | "daily" | "weekly";
            /**
             * This forces the text to appear horizontal
             */
            forceHorizontalText?: boolean;
            zIndex?: number;
            [k: string]: unknown;
          }[];
          [k: string]: unknown;
        },
        {
          title?: string;
          /**
           * The columns this day is subdivided in. Can be refered by appearsIn for events.
           *
           * @minItems 1
           */
          columns?: [string, ...string[]];
          /**
           * Tagesbemerkungen
           */
          remarks?: {
            /**
             * The text to be printed as a remark
             */
            title: string;
            /**
             * Optional Start-Time
             */
            start?: string;
            /**
             * Optional End-Time
             */
            end?: string;
            [k: string]: unknown;
          }[];
          /**
           * All events that occur on this day.
           */
          events?: {
            /**
             * Title of the event.
             */
            title: string;
            /**
             * Start time. In format HH:MM
             */
            start: string;
            /**
             * End time. In format HH:MM
             */
            end: string;
            /**
             * if the event is open-ended
             */
            openEnd?: boolean;
            /**
             * Additional information such as the responsible person or the location.
             */
            description?: string;
            /**
             * Identifer of a defined category.
             */
            category?: string;
            /**
             * Columns in which this event should appear.
             */
            appearsIn?: string[];
            /**
             * if the event repeats periodically.
             */
            repeats?: "no" | "daily" | "weekly";
            /**
             * This forces the text to appear horizontal
             */
            forceHorizontalText?: boolean;
            zIndex?: number;
            [k: string]: unknown;
          }[];
          [k: string]: unknown;
        },
        {
          title?: string;
          /**
           * The columns this day is subdivided in. Can be refered by appearsIn for events.
           *
           * @minItems 1
           */
          columns?: [string, ...string[]];
          /**
           * Tagesbemerkungen
           */
          remarks?: {
            /**
             * The text to be printed as a remark
             */
            title: string;
            /**
             * Optional Start-Time
             */
            start?: string;
            /**
             * Optional End-Time
             */
            end?: string;
            [k: string]: unknown;
          }[];
          /**
           * All events that occur on this day.
           */
          events?: {
            /**
             * Title of the event.
             */
            title: string;
            /**
             * Start time. In format HH:MM
             */
            start: string;
            /**
             * End time. In format HH:MM
             */
            end: string;
            /**
             * if the event is open-ended
             */
            openEnd?: boolean;
            /**
             * Additional information such as the responsible person or the location.
             */
            description?: string;
            /**
             * Identifer of a defined category.
             */
            category?: string;
            /**
             * Columns in which this event should appear.
             */
            appearsIn?: string[];
            /**
             * if the event repeats periodically.
             */
            repeats?: "no" | "daily" | "weekly";
            /**
             * This forces the text to appear horizontal
             */
            forceHorizontalText?: boolean;
            zIndex?: number;
            [k: string]: unknown;
          }[];
          [k: string]: unknown;
        },
        {
          title?: string;
          /**
           * The columns this day is subdivided in. Can be refered by appearsIn for events.
           *
           * @minItems 1
           */
          columns?: [string, ...string[]];
          /**
           * Tagesbemerkungen
           */
          remarks?: {
            /**
             * The text to be printed as a remark
             */
            title: string;
            /**
             * Optional Start-Time
             */
            start?: string;
            /**
             * Optional End-Time
             */
            end?: string;
            [k: string]: unknown;
          }[];
          /**
           * All events that occur on this day.
           */
          events?: {
            /**
             * Title of the event.
             */
            title: string;
            /**
             * Start time. In format HH:MM
             */
            start: string;
            /**
             * End time. In format HH:MM
             */
            end: string;
            /**
             * if the event is open-ended
             */
            openEnd?: boolean;
            /**
             * Additional information such as the responsible person or the location.
             */
            description?: string;
            /**
             * Identifer of a defined category.
             */
            category?: string;
            /**
             * Columns in which this event should appear.
             */
            appearsIn?: string[];
            /**
             * if the event repeats periodically.
             */
            repeats?: "no" | "daily" | "weekly";
            /**
             * This forces the text to appear horizontal
             */
            forceHorizontalText?: boolean;
            zIndex?: number;
            [k: string]: unknown;
          }[];
          [k: string]: unknown;
        },
        {
          title?: string;
          /**
           * The columns this day is subdivided in. Can be refered by appearsIn for events.
           *
           * @minItems 1
           */
          columns?: [string, ...string[]];
          /**
           * Tagesbemerkungen
           */
          remarks?: {
            /**
             * The text to be printed as a remark
             */
            title: string;
            /**
             * Optional Start-Time
             */
            start?: string;
            /**
             * Optional End-Time
             */
            end?: string;
            [k: string]: unknown;
          }[];
          /**
           * All events that occur on this day.
           */
          events?: {
            /**
             * Title of the event.
             */
            title: string;
            /**
             * Start time. In format HH:MM
             */
            start: string;
            /**
             * End time. In format HH:MM
             */
            end: string;
            /**
             * if the event is open-ended
             */
            openEnd?: boolean;
            /**
             * Additional information such as the responsible person or the location.
             */
            description?: string;
            /**
             * Identifer of a defined category.
             */
            category?: string;
            /**
             * Columns in which this event should appear.
             */
            appearsIn?: string[];
            /**
             * if the event repeats periodically.
             */
            repeats?: "no" | "daily" | "weekly";
            /**
             * This forces the text to appear horizontal
             */
            forceHorizontalText?: boolean;
            zIndex?: number;
            [k: string]: unknown;
          }[];
          [k: string]: unknown;
        },
        {
          title?: string;
          /**
           * The columns this day is subdivided in. Can be refered by appearsIn for events.
           *
           * @minItems 1
           */
          columns?: [string, ...string[]];
          /**
           * Tagesbemerkungen
           */
          remarks?: {
            /**
             * The text to be printed as a remark
             */
            title: string;
            /**
             * Optional Start-Time
             */
            start?: string;
            /**
             * Optional End-Time
             */
            end?: string;
            [k: string]: unknown;
          }[];
          /**
           * All events that occur on this day.
           */
          events?: {
            /**
             * Title of the event.
             */
            title: string;
            /**
             * Start time. In format HH:MM
             */
            start: string;
            /**
             * End time. In format HH:MM
             */
            end: string;
            /**
             * if the event is open-ended
             */
            openEnd?: boolean;
            /**
             * Additional information such as the responsible person or the location.
             */
            description?: string;
            /**
             * Identifer of a defined category.
             */
            category?: string;
            /**
             * Columns in which this event should appear.
             */
            appearsIn?: string[];
            /**
             * if the event repeats periodically.
             */
            repeats?: "no" | "daily" | "weekly";
            /**
             * This forces the text to appear horizontal
             */
            forceHorizontalText?: boolean;
            zIndex?: number;
            [k: string]: unknown;
          }[];
          [k: string]: unknown;
        }
      ];
      [k: string]: unknown;
    }[]
  ];
  [k: string]: unknown;
}
